'use client';

import CompareButton from '../CompareButton.jsx';
import FavoriteButton from '../FavoriteButton.jsx';
import { getLocalizedEnumLabel, getLocalizedSchoolValue } from '../../data/schools.js';

const copy = {
  ru: { found: (n) => `Найдено ${n} ${n === 1 ? 'подходящий вариант' : n < 5 ? 'подходящих варианта' : 'школ, соответствующих вашим основным критериям'}.`, limited: 'Строгие условия могли ограничить выбор по бюджету, языку обучения или другим обязательным критериям.', rank: (n) => `№${n} в рекомендациях`, match: 'совпадения', matchHelp: 'Процент показывает соответствие вашим выбранным критериям, а не общий рейтинг школы.', why: 'Почему подходит', clarify: 'Что стоит уточнить', unknownPrice: 'Стоимость уточняется', free: 'Бесплатно', month: 'в месяц', before: 'Перед окончательным выбором', disclaimer: 'Посетите школу, уточните условия поступления, актуальную стоимость и наличие мест. Рекомендации BilimChoice основаны на выбранных критериях и доступных данных каталога.', moreTitle: 'Хотите увидеть больше вариантов?', relax: 'Ослабить критерии', catalog: 'Перейти в каталог', emptyTitle: 'По заданным условиям школы не найдены', emptyText: 'Попробуйте изменить район, бюджет или другие обязательные критерии.', viewCatalog: 'Смотреть весь каталог', details: 'Подробнее', save: { add: 'Сохранить', remove: 'Сохранено' }, compare: { add: '□ Сравнить', remove: '✓ В сравнении' }, verified: 'Данные проверены', update: 'Часть сведений требует обновления' },
  kz: { found: (n) => `${n} сәйкес нұсқа табылды.`, limited: 'Қатаң шарттар бюджет, оқыту тілі немесе басқа міндетті критерийлер бойынша таңдауды шектеуі мүмкін.', rank: (n) => `Ұсынымдарда №${n}`, match: 'сәйкестік', matchHelp: 'Пайыз мектептің жалпы рейтингі емес, сіз таңдаған критерийлерге сәйкестікті көрсетеді.', why: 'Неліктен сәйкес келеді', clarify: 'Нені нақтылау керек', unknownPrice: 'Құнын нақтылау қажет', free: 'Тегін', month: 'айына', before: 'Соңғы таңдау алдында', disclaimer: 'Мектепке барып, қабылдау шарттарын, өзекті құнын және бос орындарды нақтылаңыз. BilimChoice ұсынымдары таңдалған критерийлерге және каталогтағы қолжетімді деректерге негізделген.', moreTitle: 'Көбірек нұсқа көргіңіз келе ме?', relax: 'Критерийлерді жеңілдету', catalog: 'Каталогқа өту', emptyTitle: 'Берілген шарттар бойынша мектеп табылмады', emptyText: 'Ауданды, бюджетті немесе басқа міндетті критерийлерді өзгертіп көріңіз.', viewCatalog: 'Барлық каталогты қарау', details: 'Толығырақ', save: { add: 'Сақтау', remove: 'Сақталды' }, compare: { add: '□ Салыстыру', remove: '✓ Салыстыруда' }, verified: 'Деректер тексерілді', update: 'Кейбір мәліметтерді жаңарту қажет' },
  en: { found: (n) => `${n} suitable ${n === 1 ? 'option' : 'options'} found.`, limited: 'Required conditions may have limited the choice by budget, language, or other criteria.', rank: (n) => `No. ${n} in recommendations`, match: 'match', matchHelp: 'The percentage shows alignment with your criteria, not an overall school rating.', why: 'Why it fits', clarify: 'Worth clarifying', unknownPrice: 'Tuition to be confirmed', free: 'Free', month: 'per month', before: 'Before making your final choice', disclaimer: 'Visit the school and confirm admissions, current tuition, and availability. BilimChoice recommendations are based on your criteria and available catalog data.', moreTitle: 'Want to see more options?', relax: 'Relax criteria', catalog: 'Go to catalog', emptyTitle: 'No schools found for these conditions', emptyText: 'Try changing the district, budget, or other required criteria.', viewCatalog: 'View full catalog', details: 'Details', save: { add: 'Save', remove: 'Saved' }, compare: { add: '□ Compare', remove: '✓ Comparing' }, verified: 'Data verified', update: 'Some information needs updating' }
};

export function formatRecommendationPrice(school, formatter, labels) {
  if (school.tuition_fee == null) return labels.unknownPrice;
  if (school.tuition_fee === 0) return labels.free;
  return `${formatter.format(school.tuition_fee)} ${labels.month}`;
}

export function RecommendationResultsHeader({ title, count, limited, lang }) { const l = copy[lang]; return <header className="recommendation-results__header"><h1>{title}</h1><p>{l.found(count)}</p>{limited ? <p className="recommendation-results__limited">{l.limited}</p> : null}</header>; }
export function MatchScoreBadge({ score, lang }) { if (!Number.isFinite(score)) return null; return <span className="match-score-badge"><strong>{score}%</strong> {copy[lang].match}</span>; }
export function MatchReasons({ reasons, lang }) { const items = reasons.filter(Boolean).slice(0, 4); if (!items.length) return null; return <section className="match-reasons"><h3>{copy[lang].why}</h3><ul>{items.map((reason) => <li key={reason}><span aria-hidden="true">✓</span>{reason}</li>)}</ul></section>; }
export function ConsiderationsList({ items, lang }) { const visible = [...new Set(items.filter(Boolean))].slice(0, 3); if (!visible.length) return null; return <section className="considerations-list"><h3>{copy[lang].clarify}</h3><ul>{visible.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
export function SchoolActionButtons({ school, lang }) { const l = copy[lang]; return <div className="school-action-buttons"><a className="button-link" href={`/schools/${school.slug ?? school.id}?lang=${lang}`}>{l.details}</a><FavoriteButton schoolId={school.id} labels={l.save} className="button-secondary" /><CompareButton schoolId={school.id} labels={l.compare} /></div>; }

export function RecommendedSchoolCard({ school, result, position, lang, formatter }) {
  const l = copy[lang]; const type = getLocalizedSchoolValue(school.school_type, lang); const district = getLocalizedEnumLabel('districts', school.district, lang);
  const languages = (school.instruction_languages ?? school.language_of_instruction ?? []).map((value) => getLocalizedEnumLabel('instructionLanguages', value, lang)).filter(Boolean);
  const verifiedAt = school.profile?.lastVerifiedAt ?? school.audit?.audited_at ?? school.last_verified_at;
  return <article className="recommended-school-card" data-school-id={school.id}>
    <div className="recommended-school-card__rank"><span>{l.rank(position)}</span><MatchScoreBadge score={result.score} lang={lang} /></div>
    <h2>{getLocalizedSchoolValue(school.name, lang)}</h2>
    <ul className="recommended-school-card__facts"><li>{[type, district].filter(Boolean).join(' · ')}</li>{languages.length ? <li>{languages.join(', ')}</li> : null}<li>{formatRecommendationPrice(school, formatter, l)}</li></ul>
    <div className="recommended-school-card__details"><MatchReasons reasons={result.matchedReasons ?? []} lang={lang} /><ConsiderationsList items={[...(result.missingData ?? []), ...(result.considerations ?? [])]} lang={lang} /></div>
    <SchoolActionButtons school={school} lang={lang} />
    <p className="recommended-school-card__freshness">{verifiedAt ? `${l.verified}: ${new Intl.DateTimeFormat(lang === 'kz' ? 'kk-KZ' : lang, { month: 'long', year: 'numeric' }).format(new Date(verifiedAt))}` : l.update}</p>
  </article>;
}

export function RecommendationToolbar({ labels, count, disabled, onEdit, onRestart, onSave, saved, compareHref }) { return <div className="recommendation-toolbar"><span className="visually-hidden" role="status" aria-live="polite">{labels.compareSelected}: {count}</span><div className="recommendation-toolbar__group recommendation-toolbar__edit"><button className="button-secondary" onClick={onEdit}>{labels.edit}</button><button className="button-secondary" onClick={onRestart}>{labels.restart}</button></div><div className="recommendation-toolbar__group recommendation-toolbar__selection"><button className="button-secondary" onClick={onSave}>{saved ? labels.saved : labels.save}</button><a className={`button-link recommendation-toolbar__compare${disabled ? ' is-disabled' : ''}`} href={disabled ? undefined : compareHref} aria-disabled={disabled}>{labels.compareSelected}{count ? ` (${count})` : ''}</a></div></div>; }
export function RecommendationEmptyState({ lang, onEdit }) { const l = copy[lang]; return <section className="recommendation-empty-state"><h2>{l.emptyTitle}</h2><p>{l.emptyText}</p><div><button className="hero__cta" onClick={onEdit}>{l.relax}</button><a className="button-link button-link--quiet" href={`/catalog?lang=${lang}`}>{l.viewCatalog}</a></div></section>; }
export function RecommendationDisclaimer({ lang }) { const l = copy[lang]; return <aside className="recommendation-disclaimer"><h2>{l.before}</h2><p>{l.disclaimer}</p></aside>; }
export function MoreRecommendations({ lang, onEdit }) { const l = copy[lang]; return <section className="recommendation-more"><h2>{l.moreTitle}</h2><div><button className="button-secondary" onClick={onEdit}>{l.relax}</button><a className="button-link button-link--quiet" href={`/catalog?lang=${lang}`}>{l.catalog}</a></div></section>; }
export const matchExplanation = (lang) => copy[lang].matchHelp;
